version: '2'

services:
  gatsby:
    build:
      image: joshfreeman.io/gatsby
      dockerfile: Dockerfile.gatsby
    cached: true
    working_dir: /opt
    volumes:
      - ./:/opt

  aws:
    build:
      image: joshfreeman.io/aws-cli-docker
      dockerfile: Dockerfile.aws-cli-docker
    cached: true
    working_dir: /opt
    volumes_from:
      - gatsby
    encrypted_env_file: ./aws.env.encrypted
