# from https://hub.docker.com/r/garland/aws-cli-docker/
# Used to install a more up-to-date version of AWSCLI
FROM alpine:3.6

ENV AWS_CLI_VERSION 1.15.45

RUN apk --no-cache update && \
    apk --no-cache add python py-pip py-setuptools ca-certificates groff less && \
    pip --no-cache-dir install awscli==${AWS_CLI_VERSION} && \
    rm -rf /var/cache/apk/*

WORKDIR /data

RUN aws configure set preview.cloudfront true
